language: node_js
node_js:
  - "8"
  - "10"
services:
  - mongodb
  - redis-server  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm test